### ISSUE TITLE
Collection Grant/Access Reimplementation

### ISSUE THREAD

**Issue by cd-rite** [NUWCDIVNPT/stig-manager#1289]
Collection Grants are being reimplemented. The reimplementation will more clearly distinguish Collection Privileges and Collection Access.

Collection Roles will enable sets of Collection Privileges, and have a default Access Control List.
Access control lists will specify which Assets/STIGs a user has access to, with which privileges (R/RW/none).

More info here (will be moved to this issue soon):
https://github.com/NUWCDIVNPT/stig-manager/issues/322#issuecomment-2110482330  (Read-Only Access)
Additional feature requests that will be considered for this issue:
https://github.com/NUWCDIVNPT/stig-manager/issues/849 (Consider adding accept/reject as an access level, rather than a collection-level privilege?)
https://github.com/NUWCDIVNPT/stig-manager/issues/852 (Should be satisfied by user groups)
https://github.com/NUWCDIVNPT/stig-manager/issues/729 ("dynamic" grants by label/asset/stig)
https://github.com/NUWCDIVNPT/stig-manager/issues/1182 (user groups)
https://github.com/NUWCDIVNPT/stig-manager/issues/863 (new ACL builder interface)

UI will require many changes.
New reports and assignment interfaces.
Assets/STIGs in Dashboard will probably need indicators to User indicating if they have R/RW/None access.
Should accept/reject status be considered part of "access" rather than collection privilege?
 

**Tasklists address [csmig/rbac-2](https://github.com/csmig/stig-manager/tree/rbac-2) working branch**

```[tasklist]
### API
- [x] OAS: CollectionHistorySettings -> take changes from main (max: 15, min: 0)
- [x] OAS: CollectionsProjected.owners[] does not allow for userGroup owner object
- [x] ensure sql files in api/source/service/migrations/sql/current are up to date
- [x] Calls to GET /collections/{id}?projection=users return a null user when an empty group is assigned a grant
- [x] There was an occurrence of a grantId associated to a deleted and empty userGroup that has a grant to a collection. This caused nulled out userGroup to be returned from the api. This MAY be a result of no foreign key contraint on userId in the collection_grant table. To reproduce, create an empty userGroup, give it a grant to a collection then delete the group. Doing the same process but with a user results in an an undefined userGroup being returned.
- [x] Increment AppInfo schema version due to changes
- [x] Identify and Resolve EOV response validation errors
- [x] Change `path` of operationId `getEffectiveAclByCollectionUser`
- [x] Refactor "Access Level" references , replace with "RoleId"
- [x] reviews endpoints are inconsistent in returning "access" property
- [ ] https://github.com/NUWCDIVNPT/stig-manager/issues/1458
- [x] Migration: Dont migrate user_stig_asset_map entries to collection_grant_acl where user is not currently restricted
- [x] Grant changes: On role, remove ignored ACLs for new role (ie. none). On Grantee, preserve ACLs.
- [x] putAclRulesByCollectionGrant will not enter condition "if (validated.pass.length > 0) "  when passing "[]" as an ACL.
- [x] effective access endpoint for non-restricted users with no additional acls returns empty arary (should be list of every asset/stig? Perhaps with "ACL Source" = Default or Role?) - OR - make clear in documentation that empty array implies default role access
- [x] Collection Controller -> postCklArchiveByCollection/cklb/xccdf -> call to getCollectionInfoAndCheckPermission should include minimum access level param of Restricted (currently returning 403 for restricted and full users)
- [x] Clone Collection operations need to map source ACLs to new destination ACLs
- [x] Adjust sql current files to new migration sequence
- [x] AclRuleLabelPut schema might need access property to be required.
- [x] user.lastAccess becomes top-level property, perhaps widely exposed
- [x] api not returning non-asset-based acls from queryReviewAcl
- [x] endpoint DELETE/PUT /collections/{collectionId}/grants/{grantId}
- [x] endpoint PUT/POST /collections/{collectionId}/grants accepting an array
- [x] getAssetsByStig projection restrictedUserAccess does not seem to be returning any data. Code currently in main will solve this problem I believe. PROJECTION REMOVED
- [x] GET /assets/{assetId}/checklists/{benchmarkId}/{revisionStr}, add format "json-access"
```

```[tasklist]
### UI
- [x] Collection Review if the api does not return a review for a ruleId, UI does not show the lock icon for a read only asset in bottom grid.
- [x] Collection Review Batch Edit button can become enabled when using the "select all in grid square" button even if all assets in the grid are read only.
- [x] Collection Manage -> Grants tab -> Edit ACL... Reload Icon throws an error (remove it)
- [x] App Management  -> Collections -> Click on a Collection -> On right pannel select Add Grants  -> CSV Download button.
- [x] App Management  -> Collections -> New Collection -> CSV Download button
- [x] Collection Mangement -> Add Grants -> CSV Download Button
- [x] Keep Collection Review and Asset Review asset access up to date (Won't fix)
- [x] App Management -> App info -> Collections tab -> All Field sub tab -> CSV download button (removed, Ext.ux.grid.LockingColumnModel is not supported by Ext.ux.ExportButton)
- [x] When in Colleciton Review workspace if a rule does not have any reviews, the history will not work.
- [x] See video in slack for some state mangement issues
- [x] gridToCsv export failing for: Manage Collection -> All panels except "labels"; Application Management -> Collections, Users, and User Groups
- [x] update AppInfo transformer method to support new file version
- [x] Add logic to SM/AppInfo.js to handle new AppInfo schema
- [x] collection review -> check content pane doesn't come back in subsequent tabs if tab is closed while collapsed (???)
- [x] Group Management -> changing group name errors
- [x] Group Management -> changing group name causes error
- [x] Collection Review: implement showHistory and showAssignments
- [x] Asset Checklist: Read-Only sprite missing styling
- [x] Asset Review -> Checklist header -> Sometimes shows "undefined" for either read or r/w permissions. Group Grid not initialized yet in some cases? (possibly addressed w/ an "await")
- [x] Collection Review -> editing reviews causes error: TypeError: Cannot read properties of undefined (reading 'getEl') at loadResources (http://localhost:64001/js/collectionReview.js:1945:15) at sb.afteredit (http://localhost:64001/js/collectionReview.js:1347:7)
- [x] App Management -> User/Group management popup -> save changes "live"
- [x] User Management -> Update Effective Access when tab is selected, rather than when pop-up is loaded
- [x] App Management -> Users -> Pre-register -> add a direct grant to collection causes error in DB
- [x] Collection Review allows read-only assets to be selected for Batch Edit or status-changes (POST succeeds with proper Validation Failure response for the read-only asset, no error in UI, asset retains old review). Should read-only Assets be excluded from the POST, or not selectable?
- [x] Collection Review workspace, when logged in as a user with role > 1 it is possible to Accept, Reject and Unsubmit on a read only review.
- [x] App Management -> Collections -> widen east panel
- [x] App Mangement -> Collections -> New Collection and Delete Collection cause errors
- [x] Asset Review -> Review Panel -> No longer offers "Unsubmit" button
- [x] Manage Collection -> users -> effective access popup -> use a loading animation while fetching from API
- [x] Manage Collection-> users -> effective access popup -> show user name instead of user id
- [x] Asset Review allows user to attempt to  add an attachment for read-only Asset (gets API error response in popup)
- [x] Make group "description" field optional when creating a group
- [x] User Group & User Management -> If no item is selected, disable invalid buttons
- [x] Pre-register User interface/ Grants is still old interface
- [x] User.js:1325 should be calling collections/{colIectionId}/**grants/user/**{userId}/access/**effective** (currently calling /collections/{collectionId}/users/{userId}/access
- [x] Asset Review -> Checklist -> Import Results is available to users without write access ( import "completes" w/ no changes made, marks all revies as rejected in results window)
- [x] "Edit Access List" must not show access 'none' when user has role > 1
- [x] hide "Edit Access List..." from App Manager-> Collections-> Modify dialog
- [x] Refactor Collection New Grant... interface
- [x] When deleting a grant, confirmation popup says 'About to delete Grant "undefined". Do you wish to continue?'
- [x] after creating or changing a collection grant, 'users' tab shows stale data.
- [x] Asset Review -> Checklist -> Import Reviews (Results?) -> any: Gets this error: "There is a problem with your file me.checklistFromApi.map is not a function"
- [x] Collection Review allows in-line edit, status change, and attachments to individual Reviews for read-only Assets, causing error response from API to be displayed in pop-up (status buttons, in-line editor, should be inhibited when read-only asset is selected?)
```

```[tasklist]
### Testing
- [x] Generate EOV validation failure report
- [x] Test Watcher against rbac-2 (and check client modules )
- [ ] https://github.com/NUWCDIVNPT/stig-manager/issues/1483
- [x] remove {usergroupId} endpoints
- [x] Integrate Appdata-v2 into tests
- [x] Finish Resolving test failures due to altering appdata that adds lvl1 user to a group with a new acl
- [x] complete "base" usergroup endpoint tests with new usergroup in appdata
- [x] verify all endpoints with OAS schema changes have been tested and accounted for
- [x] have new lvl1 user in a group cannot write to its "r" items
- [x] write better "base" tests for /access/effective with new lvl1 user
- [x] Alter tests in /data/acl to possibly use new groups in appdata
- [x] Check that Clone Collection operations properly map source ACLs to new destination ACLs
- [x] finish {grantId} endpoint testing
- [x] Suspect we don't have tests for postCklArchiveByCollection, since these endpoints are wrongly returning a 403 for restricted/full users (postman tests for this were v minimal)
- [x] check effective acl response performance against large data set
```
```[tasklist]
### Documentation
- [x] Document breaking changes in the API (access level -> roleId; Grant structure; .... diff w/ main)
- [ ] YouTube video explaining new Access Control and Group features
- [ ] https://github.com/NUWCDIVNPT/stig-manager/issues/1473
- [x] Update STIGMan ERD
- [x] Update RBAC spec to new best practices (e.g. privileges => capabilities)
- [x] Documentation of new features
```

**Comment by cd-rite** [comment]
# Role-Based Access Control (RBAC) components

## 1. Grant
Grant = Collection + User/Group + Role  (formerly Access Level)
### User collision
    - select any User Grant over any Group Grant(s).
    - when User matched by multiple Groups, select Grant with highest priority Role. Apply role collision rule on ties.
### Role collision
    - merge ACL resources and on Asset/STIG access collision select lowest access.  

## 2. Role
Role = Review ACL + Privileges + Priority

## 3. Review ACL
ACL = List of Rules

Rule = Resource (unique per list) + Access

### Resource (resolves to list of Asset/STIG)
    - collection (all Assets and their mapped STIGs)
    - asset (this Asset and its mapped STIGs)
    - stig (this STIG and its mapped Assets)
    - label (all Assets with this Label and their mapped STIGs)
### Access (defined from lowest to highest)
    - none (allowed for Restricted role only)
    - read
    - read/write 
### Asset/STIG collisions
    - the most specific resource is selected.
### Access collisions
    - lowest access is selected.

## 4. Privileges
### Collection
    - modify
    - delete
### Grant
    - create owner
    - create non-owner
    - modify owner
    - modify non-owner
    - delete owner
    - delete non-owner
### Asset
    - create
    - modify
    - delete
### STIG
    - map
    - unmap
### Label
    - create
    - modify
    - delete
    - map
    - unmap

## 5. Built-in Roles
For the built-in Roles:
- Each Role has a default Review ACL rule which cannot be removed.
- For all Roles, the Review ACL can be extended.
- Privileges cannot be modified or extended.

| Priority | Role       | Default ACL rule        | Privileges: Collection | Privileges: Grant                                                                                                  | Privileges: Asset              | Privileges: Label                                   | Privileges: STIG  |
|----------|------------|-------------------------|------------------------|--------------------------------------------------------------------------------------------------------------------|--------------------------------|-----------------------------------------------------|-------------------|
| 4        | Owner      |  read/write  | modify<br />delete     | create owner,<br />modify owner,<br />delete owner,<br />create non-owner,<br />modify non-owner,<br />delete non-owner | create<br />modify<br />delete | create<br />modify<br />delete<br />map<br />unmap  | map<br />unmap    |
| 3        | Manage     |  read/write  | modify                 | create non-owner,<br />modify non-owner,<br />delete non-owner                                                       | create<br />modify<br />delete | create<br />modify<br />delete<br />map<br />unmap  | map<br />unmap    |
| 2        | Full       |  read/write  | none                   | none                                                                                                               | none                           | none                                                | none              |
| 1        | Restricted | none                    | none                   | none                                                                                                               | none                           | none                                                | none              |
